version: "3"
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=my_secret_pw
      - MARIADB_DATABASE=wordpress
   # ports:
   #  - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql/
  apache:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
